services:
  gateway:
    build:
      context: .
      args:
        SERVICE: gateway
    environment:
      PORT: "8080"
      KINGDOM_URL: "http://kingdom:8081"
      ECONOMY_URL: "http://economy:8082"
      MARKET_URL: "http://market:8083"
      CIVRA_SESSION_KEY_B64: "0lea060qMsW9rocomLHXAehFrZOswdbY6jPngeBwje4="
      CIVRA_COOKIE_SECURE: ${CIVRA_COOKIE_SECURE:-false}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - kingdom
      - economy
      - market

  kingdom:
    build:
      context: .
      args:
        SERVICE: kingdom
    environment:
      PORT: "8081"

  economy:
    build:
      context: .
      args:
        SERVICE: economy
    environment:
      PORT: "8082"
      DATABASE_URL: "postgres://civra:civra@postgres:5432/civra?sslmode=disable"
    depends_on:
      - postgres

  market:
    build:
      context: .
      args:
        SERVICE: market
    environment:
      PORT: "8083"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: civra
      POSTGRES_PASSWORD: civra
      POSTGRES_DB: civra
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

